// frontend-react/src/components/Modals/TestimonialsPopup.tsx
import React, { useState, FormEvent } from 'react';
import { collection, addDoc, serverTimestamp } from 'firebase/firestore';
import { db } from '../../firebaseConfig';

interface TestimonialsPopupProps {
  isOpen: boolean;
  onClose: () => void;
  onSubmitted: () => void;
}

const TestimonialsPopup: React.FC<TestimonialsPopupProps> = ({ isOpen, onClose, onSubmitted }) => {
  const [firstName, setFirstName] = useState<string>('');
  const [lastName, setLastName] = useState<string>('');
  const [age, setAge] = useState<string>('');
  const [email, setEmail] = useState<string>('');
  const [testimonialText, setTestimonialText] = useState<string>('');
  const [isSubmitting, setIsSubmitting] = useState<boolean>(false);
  const [errorMessage, setErrorMessage] = useState<string>('');
  const [successMessage, setSuccessMessage] = useState<string>('');

  const closePopup = () => {
    onClose();
    // Reset form state
    setFirstName('');
    setLastName('');
    setAge('');
    setEmail('');
    setTestimonialText('');
    setErrorMessage('');
    setSuccessMessage('');
  };

  const validateEmail = (email: string): boolean => {
    const re = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    return re.test(email);
  };

  const submitTestimonial = async () => {
    // Form validation
    if (!firstName.trim()) {
      setErrorMessage('Veuillez entrer votre prénom');
      return;
    }
    
    if (!lastName.trim()) {
      setErrorMessage('Veuillez entrer votre nom');
      return;
    }
    
    if (!age) {
      setErrorMessage('Veuillez entrer votre âge');
      return;
    }
    
    if (isNaN(Number(age)) || Number(age) <= 0) {
      setErrorMessage('Veuillez entrer un âge valide');
      return;
    }
    
    if (!email.trim()) {
      setErrorMessage('Veuillez entrer votre email');
      return;
    }
    
    if (!validateEmail(email)) {
      setErrorMessage('Veuillez entrer un email valide');
      return;
    }
    
    if (!testimonialText.trim()) {
      setErrorMessage('Veuillez entrer un témoignage');
      return;
    }

    try {
      setIsSubmitting(true);
      setErrorMessage('');
      
      // Add to Firestore
      const testimonialsRef = collection(db, 'testimonials');
      await addDoc(testimonialsRef, {
        firstName: firstName.trim(),
        lastName: lastName.trim(),
        age: Number(age),
        email: email.trim(),
        text: testimonialText.trim(),
        createdAt: serverTimestamp(),
        approved: false // Add an approval flag for moderation
      });
      
      setSuccessMessage('Merci pour votre témoignage !');
      
      // Reset form fields
      setFirstName('');
      setLastName('');
      setAge('');
      setEmail('');
      setTestimonialText('');
      
      // Close popup after 2 seconds
      setTimeout(() => {
        onSubmitted();
        closePopup();
      }, 2000);
      
    } catch (error: unknown) {
      console.error('Erreur lors de l\'envoi du témoignage:', error);
      const firebaseError = error as Error;
      setErrorMessage(`Une erreur est survenue: ${firebaseError.message}`);
    } finally {
      setIsSubmitting(false);
    }
  };

  if (!isOpen) return null;

  return (
    <div className="popup-overlay" onClick={closePopup}>
      <div className="popup-content" onClick={(e) => e.stopPropagation()}>
        <div className="popup-header">
          <h2>Partagez votre expérience</h2>
          <button className="close-button" onClick={closePopup}>×</button>
        </div>
        
        <div className="popup-body">
          {errorMessage && (
            <div className="error-message">{errorMessage}</div>
          )}
          {successMessage && (
            <div className="success-message">{successMessage}</div>
          )}
          
          <div className="form-row">
            <div className="form-group">
              <label htmlFor="firstName">Prénom</label>
              <input
                id="firstName"
                value={firstName}
                onChange={(e) => setFirstName(e.target.value)}
                type="text"
                placeholder="Votre prénom"
                disabled={isSubmitting}
              />
            </div>
            
            <div className="form-group">
              <label htmlFor="lastName">Nom</label>
              <input
                id="lastName"
                value={lastName}
                onChange={(e) => setLastName(e.target.value)}
                type="text"
                placeholder="Votre nom"
                disabled={isSubmitting}
              />
            </div>
          </div>
          
          <div className="form-row">
            <div className="form-group">
              <label htmlFor="age">Âge</label>
              <input
                id="age"
                value={age}
                onChange={(e) => setAge(e.target.value)}
                type="number"
                min="1"
                max="120"
                placeholder="Votre âge"
                disabled={isSubmitting}
              />
            </div>
            
            <div className="form-group">
              <label htmlFor="email">Email</label>
              <input
                id="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                type="email"
                placeholder="Votre email"
                disabled={isSubmitting}
              />
            </div>
          </div>
          
          <div className="form-group">
            <label htmlFor="testimonial">Votre témoignage</label>
            <textarea 
              id="testimonial" 
              value={testimonialText}
              onChange={(e) => setTestimonialText(e.target.value)}
              placeholder="Partagez votre expérience avec MAX..."
              rows={4}
              disabled={isSubmitting}
            />
          </div>
          
          <div className="form-actions">
            <button 
              className="submit-button" 
              onClick={submitTestimonial} 
              disabled={isSubmitting}
            >
              {isSubmitting ? 'Envoi en cours...' : 'Envoyer'}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TestimonialsPopup;

// max/src/components/Modals/TestimonialsPopup.vue
<script setup>
import { ref } from 'vue';
import { collection, addDoc, serverTimestamp } from 'firebase/firestore';
import { db } from '../../firebaseConfig';

const props = defineProps({
  isOpen: {
    type: Boolean,
    default: false
  }
});

const emit = defineEmits(['close', 'submitted']);

const firstName = ref('');
const lastName = ref('');
const age = ref('');
const email = ref('');
const testimonialText = ref('');
const isSubmitting = ref(false);
const errorMessage = ref('');
const successMessage = ref('');

const closePopup = () => {
  emit('close');
  // Reset form state
  firstName.value = '';
  lastName.value = '';
  age.value = '';
  email.value = '';
  testimonialText.value = '';
  errorMessage.value = '';
  successMessage.value = '';
};

const validateEmail = (email) => {
  const re = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  return re.test(email);
};

const submitTestimonial = async () => {
  // Form validation
  if (!firstName.value.trim()) {
    errorMessage.value = 'Veuillez entrer votre prénom';
    return;
  }
  
  if (!lastName.value.trim()) {
    errorMessage.value = 'Veuillez entrer votre nom';
    return;
  }
  
  if (!age.value) {
    errorMessage.value = 'Veuillez entrer votre âge';
    return;
  }
  
  if (isNaN(Number(age.value)) || Number(age.value) <= 0) {
    errorMessage.value = 'Veuillez entrer un âge valide';
    return;
  }
  
  if (!email.value.trim()) {
    errorMessage.value = 'Veuillez entrer votre email';
    return;
  }
  
  if (!validateEmail(email.value)) {
    errorMessage.value = 'Veuillez entrer un email valide';
    return;
  }
  
  if (!testimonialText.value.trim()) {
    errorMessage.value = 'Veuillez entrer un témoignage';
    return;
  }

  try {
    isSubmitting.value = true;
    errorMessage.value = '';
    
    // Add to Firestore
    const testimonialsRef = collection(db, 'testimonials');
    await addDoc(testimonialsRef, {
      firstName: firstName.value.trim(),
      lastName: lastName.value.trim(),
      age: Number(age.value),
      email: email.value.trim(),
      text: testimonialText.value.trim(),
      createdAt: serverTimestamp(),
      approved: false // Add an approval flag for moderation
    });
    
    successMessage.value = 'Merci pour votre témoignage !';
    
    // Reset form fields
    firstName.value = '';
    lastName.value = '';
    age.value = '';
    email.value = '';
    testimonialText.value = '';
    
    // Close popup after 2 seconds
    setTimeout(() => {
      emit('submitted');
      closePopup();
    }, 2000);
    
  } catch (error) {
    console.error('Erreur lors de l\'envoi du témoignage:', error);
    errorMessage.value = `Une erreur est survenue: ${error.message}`;
  } finally {
    isSubmitting.value = false;
  }
};
</script>

<template>
  <div v-if="isOpen" class="popup-overlay" @click="closePopup">
    <div class="popup-content" @click.stop>
      <div class="popup-header">
        <h2>Partagez votre expérience</h2>
        <button class="close-button" @click="closePopup">×</button>
      </div>
      
      <div class="popup-body">
        <div v-if="errorMessage" class="error-message">{{ errorMessage }}</div>
        <div v-if="successMessage" class="success-message">{{ successMessage }}</div>
        
        <div class="form-row">
          <div class="form-group">
            <label for="firstName">Prénom</label>
            <input
              id="firstName"
              v-model="firstName"
              type="text"
              placeholder="Votre prénom"
              :disabled="isSubmitting"
            />
          </div>
          
          <div class="form-group">
            <label for="lastName">Nom</label>
            <input
              id="lastName"
              v-model="lastName"
              type="text"
              placeholder="Votre nom"
              :disabled="isSubmitting"
            />
          </div>
        </div>
        
        <div class="form-row">
          <div class="form-group">
            <label for="age">Âge</label>
            <input
              id="age"
              v-model="age"
              type="number"
              min="1"
              max="120"
              placeholder="Votre âge"
              :disabled="isSubmitting"
            />
          </div>
          
          <div class="form-group">
            <label for="email">Email</label>
            <input
              id="email"
              v-model="email"
              type="email"
              placeholder="Votre email"
              :disabled="isSubmitting"
            />
          </div>
        </div>
        
        <div class="form-group">
          <label for="testimonial">Votre témoignage</label>
          <textarea 
            id="testimonial" 
            v-model="testimonialText"
            placeholder="Partagez votre expérience avec MAX..."
            rows="4"
            :disabled="isSubmitting"
          ></textarea>
        </div>
        
        <div class="form-actions">
            <button 
            class="submit-button" 
            @click="submitTestimonial" 
            :disabled="isSubmitting || cooldown">
            {{ isSubmitting ? 'Envoi en cours...' : cooldown ? 'Envoyé !' : 'Envoyer' }}
            </button>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.popup-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 1000;
  backdrop-filter: blur(5px);
}

.popup-content {
  background-color: white;
  border-radius: 8px;
  width: 90%;
  max-width: 600px;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.15);
  overflow: hidden;
  animation: popup-appear 0.3s ease-out;
}

@keyframes popup-appear {
  from {
    opacity: 0;
    transform: scale(0.9);
  }
  to {
    opacity: 1;
    transform: scale(1);
  }
}

.popup-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 16px 20px;
  background-color: #1C5372;
  color: white;
}

.popup-header h2 {
  font-size: 1.25rem;
  margin: 0;
}

.close-button {
  background: none;
  border: none;
  color: white;
  font-size: 1.5rem;
  cursor: pointer;
  padding: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  width: 30px;
  height: 30px;
  transition: background-color 0.2s;
  border-radius: 50%;
}

.close-button:hover {
  background-color: rgba(255, 255, 255, 0.2);
}

.popup-body {
  padding: 20px;
}

.form-row {
  display: flex;
  gap: 16px;
  margin-bottom: 16px;
}

.form-row .form-group {
  flex: 1;
  margin-bottom: 0;
}

.form-group {
  margin-bottom: 16px;
}

.form-group label {
  display: block;
  margin-bottom: 8px;
  font-weight: 600;
  color: #333;
}

input, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid #ddd;
  border-radius: 4px;
  font-size: 1rem;
  font-family: inherit;
}

textarea {
  resize: vertical;
}

input:focus, textarea:focus {
  outline: none;
  border-color: #1C5372;
  box-shadow: 0 0 0 2px rgba(28, 83, 114, 0.2);
}

input:disabled, textarea:disabled {
  background-color: #f7f7f7;
  cursor: not-allowed;
}

.form-actions {
  display: flex;
  justify-content: flex-end;
}

.submit-button {
  background-color: #1C5372;
  color: white;
  border: none;
  padding: 10px 20px;
  border-radius: 4px;
  font-size: 1rem;
  cursor: pointer;
  transition: background-color 0.2s;
}

.submit-button:hover {
  background-color: #164259;
}

.submit-button:disabled {
  background-color: #94a3b8;
  cursor: not-allowed;
}

.error-message {
  padding: 10px;
  background-color: #fee2e2;
  color: #b91c1c;
  border-radius: 4px;
  margin-bottom: 16px;
}

.success-message {
  padding: 10px;
  background-color: #dcfce7;
  color: #166534;
  border-radius: 4px;
  margin-bottom: 16px;
}

@media (max-width: 640px) {
  .form-row {
    flex-direction: column;
    gap: 16px;
  }
  
  .form-row .form-group {
    margin-bottom: 0;
  }
}
</style>
