// max/src/components/Abonnement.vue
<template>
    <div id="app">
      <h1 class="title">ABONNEMENT</h1>
      <p class="subtitle">
        Choisissez l'abonnement qui vous convient et profitez pleinement de Max.<br />
        <span class="subtitle-note">Sans engagement, annulable à tout moment.</span>
      </p>
      <div class="plans-container">
        <PlanCard
          :title="'Plan Free (Gratuit)'"
          :price="'0 €'"
          :description="'Commencer gratuitement'"
          :features="[
            'Interactions étendues (10 sessions par jour).',
            'Choix du ton et de la personnalité de Max (bienveillant, neutre ou direct).',
            'Suggestions de ressources personnalisées selon vos besoins.',
          ]"
          :buttonText="'Gratuit'"
          :buttonStyle="'secondary'"
        />
        <PlanCard
          :title="'Plan Premium'"
          :price="'14,99€ / mois'"
          :description="'Essai gratuit (0€ - 14 jours)'"
          :features="[
            'Accès illimité à Max pour discuter à tout moment.',
            'Envoi de photos, vidéos et documents pour des conseils précis.',
            'Personnalisation illimitée : Ajusté à votre style, ton et besoins.',
            'Analyse approfondie pour des conseils et stratégies sur mesure.',
            'Rapports mensuels pour suivre vos progrès émotionnels.',
            'Réductions sur les consultations recommandées via Max.',
          ]"
          :buttonText="'Passer À Premium'"
          :buttonStyle="'primary'"
          highlight
        />
        <PlanCard
          :title="'Plan Mensuel'"
          :price="'9,99€ / mois'"
          :description="'Essai gratuit (0€ - 7 jours)'"
          :features="[
            'Accès illimité à Max pour discuter à tout moment.',
            'Envoi de photos, vidéos et documents pour des conseils précis.',
            'Personnalisation illimitée : Ajusté à votre style, ton et besoins.',
            'Analyse approfondie pour des conseils et stratégies sur mesure.',
          ]"
          :buttonText="'Passer Plan Mensuel'"
          :buttonStyle="'secondary'"
        />
        
        
      </div>
    </div>
 
  </template>
  
  <script>
  import PlanCard from "../components/PlanCard.vue";
  
  export default {
    components: {
      PlanCard,
    },
  };
  </script>
  
  <style scoped>
  #app {
    text-align: center;
    padding: 20px;
    background-color: #E9E9E9;
  }
  
  .title {
    font-size: 2rem;
    font-weight: bold;
    margin-bottom: 10px;
  }
  
  .subtitle {
    font-size: 1.2rem;
    color: #666;
    margin-bottom: 40px;
  }
  
  .subtitle-note {
    font-size: 0.9rem;
    font-weight: normal;
  }
  
  .plans-container {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    gap: 20px;
  }
  </style>

// frontend-react/src/components/Abonnement.jsx
import React, { useEffect } from 'react';
import PlanCard from './PlanCard.jsx';
import AOS from 'aos';
import 'aos/dist/aos.css';

const Abonnement = ({ className }) => {
  useEffect(() => {
    AOS.init();
  }, []);

  return (
    <div id="app" className={className}>
      <div data-aos="fade-up" data-aos-duration="500" data-aos-delay="200">
        <h1 id="title" className="title">ABONNEMENT</h1>
        <p className="subtitle">
          Choisissez l'abonnement qui vous convient et profitez pleinement de Max.<br />
          <span className="subtitle-note">Sans engagement, annulable à tout moment.</span>
        </p>
        
        <div className="plans-container">
          <PlanCard
            title="Version Essai"
            price="0 €"
            description="Limite de 10 échanges"
            features={[
              'Chatbot Max (écoute empathique)',
            ]}
            buttonText="Gratuit"
            buttonStyle="secondary"
          />
          
          <PlanCard
            title="Premium"
            price="15€/mois ou 4,99€/semaine"
            description="Sans engagement ou avec abonnement"
            features={[
              'Suivi émotionnel personnalisé',
              'Statistiques bien-être',
              'Recommendation des pros (coach)',
              'Contenus exclusifs audio/vidéo',
              'Journal émotionnel simple',
            ]}
            buttonText="Plan Premium"
            buttonStyle="primary"
            highlight={true}
          />
          
          <PlanCard
            title="Campus"
            price="8€/mois"
            description="Pris en charge par l'établissement"
            features={[
              'Offre Premium à tous les étudiants concernés',
            ]}
            buttonText="Plan Campus"
            buttonStyle="secondary"
          />
        </div>
      </div>
    </div>
  );
};

export default Abonnement;
