// max/src/components/Authentication/AuthUser.vue
<script>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import NavBar from '../../layout/NavBar.vue'
import Footer from '../../layout/footer.vue'

export default {
  name: 'AuthPage',
  components: {
    NavBar,
    Footer
  },
  data() {
    return {
      mode: 'login',
      error: '',
      loading: false,
      form: {
        firstName: '',
        lastName: '',
        birthDate: '',
        email: '',
        password: '',
        confirmPassword: '',
        acceptTerms: false
      }
    };
  },
  methods: {
    toggleMode() {
      this.mode = this.mode === 'login' ? 'register' : 'login';
      this.error = '';
    },
    validateForm() {
      this.error = '';
      
      if (this.mode === 'register') {
        if (!this.form.firstName.trim()) {
          this.error = 'Le prénom est requis';
          return false;
        }
        if (!this.form.lastName.trim()) {
          this.error = 'Le nom est requis';
          return false;
        }
        if (!this.form.birthDate) {
          this.error = 'La date de naissance est requise';
          return false;
        }
        if (this.form.password !== this.form.confirmPassword) {
          this.error = 'Les mots de passe ne correspondent pas';
          return false;
        }
        if (!this.form.acceptTerms) {
          this.error = 'Veuillez accepter les termes de confidentialité';
          return false;
        }
      }
      
      if (!this.form.email.trim()) {
        this.error = 'L\'email est requis';
        return false;
      }
      if (!this.form.password) {
        this.error = 'Le mot de passe est requis';
        return false;
      }
      
      return true;
    },
    async handleSubmit() {
  if (!this.validateForm()) return;

  this.loading = true;

  try {
    if (this.mode === 'login') {
      const response = await fetch('http://185.98.139.244/api/auth/login', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          email: this.form.email,
          password: this.form.password
        })
      });

      const data = await response.json();

      if (!response.ok) {
        this.error = data.message || 'Erreur lors de la connexion.';
        return;
      }

      localStorage.setItem('token', data.token);
      localStorage.setItem('name', data.user.firstName + ' ' + data.user.lastName);

      //console.log('data', data);
      //console.log('token', data.token);
      //console.log('name', data.user.firstName + ' ' + data.user.lastName);
    
      this.$router.push('/chatbot');
    } else {
      // Calculer l'âge à partir de la date de naissance
      const birthDate = new Date(this.form.birthDate);
      const ageDiffMs = Date.now() - birthDate.getTime();
      const ageDate = new Date(ageDiffMs);
      const age = Math.abs(ageDate.getUTCFullYear() - 1970);

      const response = await fetch('http://185.98.139.244/api/auth/register', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          firstName: this.form.firstName,
          lastName: this.form.lastName,
          age: age,
          email: this.form.email,
          password: this.form.password
        })
      });

      const data = await response.json();

      if (!response.ok) {
        this.error = data.message || 'Erreur lors de l\'inscription.';
        return;
      }

      this.$router.push('/chatbot');  // Redirige vers la page de vérification ou login
    }
  } catch (error) {
    this.error = 'Une erreur est survenue. Veuillez réessayer.';
    console.error('Auth error:', error);
  } finally {
    this.loading = false;
  }
}
,
    goToLogin() {
      this.mode = 'login';
    },
    goToRegister() {
      this.mode = 'register';
    }
  }
};
</script>

<template>
  <div class="login-container">
    <NavBar/>
    
    <div class="login-form-container">
    
      
      <form @submit.prevent="handleSubmit" class="login-form">
        <div class="login-form-header">
        <h1>MAX</h1>
        <p>{{ mode === 'login' ? 'Welcome Back' : 'Rejoignez Max' }}</p>
      </div>
        <!-- Message d'erreur -->
        <div v-if="error" class="error-message">
          {{ error }}
        </div>
        
        <template v-if="mode === 'register'">
          <div class="form-row">
            
            <div class="form-group">
              <label for="firstName">Prénom</label>
              <input
                id="firstName"
                type="text"
                v-model="form.firstName"
                placeholder="Votre prénom"
                class="login-input"
                required
              />
            </div>
            
            <div class="form-group">
              <label for="lastName">Nom</label>
              <input
                id="lastName"
                type="text"
                v-model="form.lastName"
                placeholder="Votre nom"
                class="login-input"
                required
              />
            </div>
          </div>
          
          <div class="form-group">
            <label for="birthDate">Date de naissance</label>
            <input
              id="birthDate"
              type="date"
              v-model="form.birthDate"
              class="login-input"
              required
            />
          </div>
        </template>
        
        <div class="form-group">
          <label for="email">Email</label>
          <input
            id="email"
            type="email"
            v-model="form.email"
            placeholder="example@email.com"
            class="login-input"
            required
          />
        </div>
        
        <div class="form-group">
          <label for="password">Mot de passe</label>
          <input
            id="password"
            type="password"
            v-model="form.password"
            placeholder="Votre mot de passe"
            class="login-input"
            required
          />
        </div>
        
        <template v-if="mode === 'register'">
          <div class="form-group">
            <label for="confirmPassword">Confirmez le mot de passe</label>
            <input
              id="confirmPassword"
              type="password"
              v-model="form.confirmPassword"
              placeholder="Confirmez votre mot de passe"
              class="login-input"
              required
            />
          </div>
          
          <div class="terms-checkbox">
            <input 
              type="checkbox" 
              id="terms" 
              v-model="form.acceptTerms"
            />
            <label for="terms">Accepter les Termes de Confidentialité</label>
          </div>
        </template>
        
        <template v-else>
          <div class="forgot-password">
            <button type="button" class="forgot-password-btn">
              Mot de passe oublié ?
            </button>
          </div>
        </template>
        
        <button type="submit" class="login-submit-btn" :disabled="loading">
          {{ loading ? (mode === 'login' ? 'Connexion...' : 'Inscription...') : (mode === 'login' ? 'Se connecter' : 'S\'inscrire') }}
        </button>
        
        <p class="login-terms">
          {{ mode === 'login' ? "Pas encore de compte ?" : "Déjà inscrit(e) ?" }}
          <button type="button" class="login-terms-button" @click="toggleMode">
            {{ mode === 'login' ? "S'inscrire ici" : "Se connecter ici" }}
          </button>
        </p>
        
        <div class="divider">
          <span>ou</span>
        </div>
        
        <div class="social-login">
          <button type="button" class="social-button google-button">
            <svg class="social-icon" viewBox="0 0 24 24" width="18" height="18">
              <path d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" fill="#4285F4"/>
              <path d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" fill="#34A853"/>
              <path d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z" fill="#FBBC05"/>
              <path d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" fill="#EA4335"/>
              <path d="M1 1h22v22H1z" fill="none"/>
            </svg>
            {{ mode === 'login' ? 'Connexion avec Google' : 'Inscription avec Google' }}
          </button>
      
        </div>
      </form>
    </div>
    
    <Footer />
  </div>
</template>

<style scoped>
.login-container {
  background: linear-gradient(104.32deg, #1C5372 0%, #90DBF5 57.67%, #FFD2C7 95.58%);
  position: relative;
  overflow: hidden;
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}

.login-form-container {
  width: 100%;
  max-width: 40rem;
  margin: 2rem auto;
  padding: 2rem;
  flex: 1;
}

.login-form {
  background: rgba(255, 255, 255, 0.089);
  backdrop-filter: blur(10px);
  padding: 2rem;
  border-radius: 1rem;
  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.1);
  position: relative;
}

/* Utiliser un pseudo-élément pour créer la bordure en dégradé */
.login-form::before {
  content: "";
  position: absolute;
  inset: 0; /* équivalent à top:0, right:0, bottom:0, left:0 */
  border-radius: 1rem;
  padding: 1px; /* épaisseur de la bordure */
  background: linear-gradient(45deg, #12c2e9, #c471ed, #f7797d);
  -webkit-mask: 
    linear-gradient(#fff 0 0) content-box, 
    linear-gradient(#fff 0 0);
  -webkit-mask-composite: xor;
  mask-composite: exclude;
  pointer-events: none;
}

.login-form-header {
  text-align: center;
  margin-bottom: 2rem;
}

.login-form-header h1 {
  color: white;
  font-size: 3.75rem;
  font-weight: bold;
  margin-bottom: 1rem;
  text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2);
}

.login-form-header p {
  color: rgba(255, 255, 255, 0.9);
  font-size: 1.25rem;
}

.form-row {
  display: flex;
  gap: 1rem;
  margin-bottom: 1rem;
}

.form-row .form-group {
  flex: 1;
}

.form-group {
  margin-bottom: 1.5rem;
  width: 100%;
}

.form-group label {
  display: block;
  color: white;
  font-size: 0.875rem;
  margin-bottom: 0.5rem;
  font-weight: 500;
}

.login-input {
  width: 100%;
  padding: 1rem;
  border: 1px solid rgba(255, 255, 255, 0.2);
  border-radius: 0.5rem;
  background: rgba(255, 255, 255, 0.9);
  font-size: 1rem;
  transition: all 0.3s ease;
}

.login-input:focus {
  outline: none;
  box-shadow: 0 0 0 2px rgba(37, 99, 235, 0.5);
  transform: translateY(-2px);
}

.error-message {
  background-color: rgba(239, 68, 68, 0.1);
  color: rgb(239, 68, 68);
  padding: 1rem;
  border-radius: 0.5rem;
  margin-bottom: 1.5rem;
  text-align: center;
  border: 1px solid rgba(239, 68, 68, 0.3);
}

.forgot-password {
  text-align: right;
  margin-bottom: 1.5rem;
}

.forgot-password-btn {
  background: none;
  border: none;
  color: white;
  font-size: 0.9rem;
  text-decoration: underline;
  cursor: pointer;
  transition: opacity 0.3s ease;
}

.forgot-password-btn:hover {
  opacity: 0.8;
}

.login-submit-btn {
  width: 100%;
  padding: 1rem;
  background: #76bbd7;
  color: white;
  border: none;
  border-radius: 0.5rem;
  font-weight: 600;
  font-size: 1.1rem;
  text-transform: uppercase;
  cursor: pointer;
  transition: all 0.3s ease;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
}

.login-submit-btn:hover:not(:disabled) {
  background: #1d4ed8;
  transform: translateY(-2px);
  box-shadow: 0 6px 8px rgba(0, 0, 0, 0.2);
}

.login-submit-btn:disabled {
  opacity: 0.7;
  cursor: not-allowed;
}

.login-terms {
  text-align: center;
  color: white;
  font-size: 0.9rem;
  margin-top: 1.5rem;
}

.login-terms-button {
  background: none;
  border: none;
  color: white;
  transition: all 0.3s ease;
  text-decoration: underline;
  cursor: pointer;
  font-weight: 600;
}

.login-terms-button:hover {
  opacity: 0.8;
}

.terms-checkbox {
  display: flex;
  align-items: center;
  margin: 1.5rem 0;
}

.terms-checkbox input {
  margin-right: 0.5rem;
  cursor: pointer;
}

.terms-checkbox label {
  color: white;
  font-size: 0.875rem;
  margin-bottom: 0;
  cursor: pointer;
}

.divider {
  display: flex;
  align-items: center;
  margin: 1.5rem 0;
}

.divider::before,
.divider::after {
  content: "";
  flex: 1;
  border-bottom: 1px solid rgba(255, 255, 255, 0.2);
}

.divider span {
  padding: 0 0.75rem;
  color: rgba(255, 255, 255, 0.6);
  font-size: 0.875rem;
}

.social-login {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
}

.social-button {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  padding: 0.75rem;
  border-radius: 0.5rem;
  border: none;
  background: white;
  color: #333;
  font-size: 0.875rem;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.3s ease;
}

.social-button:hover {
  background: #f8f8f8;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
}

.social-icon {
  margin-right: 0.75rem;
}

@media (max-width: 768px) {
  .login-form-container {
    padding: 1.5rem;
    max-width: 100%;
  }

  .login-form-header h1 {
    font-size: 3rem;
  }

  .login-form {
    padding: 1.5rem;
  }
  
  .form-row {
    flex-direction: column;
    gap: 1rem;
  }
}
</style>

// frontend-react/src/components/Authentication/AuthUser.tsx
import React, { useState, FormEvent, ChangeEvent } from 'react';
import { useNavigate } from 'react-router-dom';
import NavBar from '../../layout/NavBar';
import Footer from '../../layout/Footer';

interface FormData {
  firstName: string;
  lastName: string;
  birthDate: string;
  email: string;
  password: string;
  confirmPassword: string;
  acceptTerms: boolean;
}

const AuthUser: React.FC = () => {
  const navigate = useNavigate();
  const [mode, setMode] = useState<'login' | 'register'>('login');
  const [error, setError] = useState<string>('');
  const [loading, setLoading] = useState<boolean>(false);
  const [form, setForm] = useState<FormData>({
    firstName: '',
    lastName: '',
    birthDate: '',
    email: '',
    password: '',
    confirmPassword: '',
    acceptTerms: false
  });

  const toggleMode = (): void => {
    setMode(mode === 'login' ? 'register' : 'login');
    setError('');
  };

  const handleInputChange = (e: ChangeEvent<HTMLInputElement>): void => {
    const { name, value, type, checked } = e.target;
    setForm(prev => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : value
    }));
  };

  const validateForm = () => {
    setError('');
    
    if (mode === 'register') {
      if (!form.firstName.trim()) {
        setError('Le prénom est requis');
        return false;
      }
      if (!form.lastName.trim()) {
        setError('Le nom est requis');
        return false;
      }
      if (!form.birthDate) {
        setError('La date de naissance est requise');
        return false;
      }
      if (form.password !== form.confirmPassword) {
        setError('Les mots de passe ne correspondent pas');
        return false;
      }
      if (!form.acceptTerms) {
        setError('Veuillez accepter les termes de confidentialité');
        return false;
      }
    }
    
    if (!form.email.trim()) {
      setError('L\'email est requis');
      return false;
    }
    if (!form.password) {
      setError('Le mot de passe est requis');
      return false;
    }
    
    return true;
  };

  const handleSubmit = async (e: FormEvent<HTMLFormElement>): Promise<void> => {
    e.preventDefault();
    if (!validateForm()) return;

    setLoading(true);

    try {
      if (mode === 'login') {
        const response = await fetch('http://localhost:3000/api/auth/login', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            email: form.email,
            password: form.password
          })
        });

        const data = await response.json();

        if (!response.ok) {
          setError(data.message || 'Erreur lors de la connexion.');
          return;
        }

        localStorage.setItem('token', data.token);
        localStorage.setItem('name', data.user.firstName + ' ' + data.user.lastName);
        localStorage.setItem('userId', data.user.id);
      
        navigate('/dashboard');
      } else {
        // Calculer l'âge à partir de la date de naissance
        const birthDate = new Date(form.birthDate);
        const ageDiffMs = Date.now() - birthDate.getTime();
        const ageDate = new Date(ageDiffMs);
        const age = Math.abs(ageDate.getUTCFullYear() - 1970);

        const response = await fetch('http://localhost:3000/api/auth/register', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            firstName: form.firstName,
            lastName: form.lastName,
            age: age,
            email: form.email,
            password: form.password
          })
        });

        const data = await response.json();

        if (!response.ok) {
          setError(data.message || 'Erreur lors de l\'inscription.');
          return;
        }

        localStorage.setItem('token', data.token);
        localStorage.setItem('name', data.user.firstName + ' ' + data.user.lastName);
        localStorage.setItem('userId', data.user.id);

        navigate('/dashboard');
      }
    } catch (error) {
      setError('Une erreur est survenue. Veuillez réessayer.');
      console.error('Auth error:', error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="login-container">
      <NavBar />
      
      <div className="login-form-container">
        <form onSubmit={handleSubmit} className="login-form">
          <div className="login-form-header">
            <img src="/src/assets/img/hero/logomax.png" alt="MAX" className="login-logo-auth" />
            <h2 className="login-welcome">Bienvenue</h2>
            <p className="login-subtitle">Découvrez une nouvelle façon d’être accompagné au quotidien.</p>

          </div>

          {/* Message d'erreur */}
          {error && (
            <div className="error-message">
              {error}
            </div>
          )}
          
          {mode === 'register' && (
            <>
              <div className="form-row">
                <div className="form-group">
                  <label htmlFor="firstName">Prénom</label>
                  <input
                    id="firstName"
                    name="firstName"
                    type="text"
                    value={form.firstName}
                    onChange={handleInputChange}
                    placeholder="Votre prénom"
                    className="login-input"
                    required
                  />
                </div>
                
                <div className="form-group">
                  <label htmlFor="lastName">Nom</label>
                  <input
                    id="lastName"
                    name="lastName"
                    type="text"
                    value={form.lastName}
                    onChange={handleInputChange}
                    placeholder="Votre nom"
                    className="login-input"
                    required
                  />
                </div>
              </div>
              
              <div className="form-group">
                <label htmlFor="birthDate">Date de naissance</label>
                <input
                  id="birthDate"
                  name="birthDate"
                  type="date"
                  value={form.birthDate}
                  onChange={handleInputChange}
                  className="login-input"
                  required
                />
              </div>
            </>
          )}
          
          <div className="form-group">
            <label htmlFor="email">Email</label>
            <input
              id="email"
              name="email"
              type="email"
              value={form.email}
              onChange={handleInputChange}
              placeholder="votre@email.com"
              className="login-input"
              required
            />
          </div>
          
          <div className="form-group">
            <label htmlFor="password">Mot de passe</label>
            <input
              id="password"
              name="password"
              type="password"
              value={form.password}
              onChange={handleInputChange}
              placeholder="Votre mot de passe"
              className="login-input"
              required
            />
          </div>
          
          {mode === 'register' && (
            <>
              <div className="form-group">
                <label htmlFor="confirmPassword">Confirmer le mot de passe</label>
                <input
                  id="confirmPassword"
                  name="confirmPassword"
                  type="password"
                  value={form.confirmPassword}
                  onChange={handleInputChange}
                  placeholder="Confirmez votre mot de passe"
                  className="login-input"
                  required
                />
              </div>
              
              <div className="checkbox-group">
                <input
                  id="acceptTerms"
                  name="acceptTerms"
                  type="checkbox"
                  checked={form.acceptTerms}
                  onChange={handleInputChange}
                  className="login-checkbox"
                  required
                />
                <label htmlFor="acceptTerms">
                  J'accepte les <a href="/politics/conditions-utilisation" target="_blank">conditions d'utilisation</a> et la <a href="/politics/politique-confidentialites" target="_blank">politique de confidentialité</a>
                </label>
              </div>
            </>
          )}
          
          <button 
            type="submit" 
            className="login-button" 
            disabled={loading}
          >
            {loading ? 'Chargement...' : (mode === 'login' ? 'Connexion' : 'Inscription')}
          </button>
          
          <div className="toggle-mode">
            <p>
              {mode === 'login' ? 'Vous n avez pas encore rejoint MAX ?' : 'Si vous êtes déjà inscrit ?'}
              <button type="button" onClick={toggleMode} className="toggle-link">
                {mode === 'login' ? 'Inscription ici' : 'Se connecter'}
              </button>
            </p>
          </div>

          <div className="social-divider">
            <span>Ou</span>
          </div>

          <div className="social-login-buttons">
            <button type="button" className="social-btn google-btn">
              <svg width="18" height="18" viewBox="0 0 18 18" xmlns="http://www.w3.org/2000/svg">
                <path d="M17.64 9.2c0-.637-.057-1.251-.164-1.84H9v3.481h4.844c-.209 1.125-.843 2.078-1.796 2.717v2.258h2.908c1.702-1.567 2.684-3.874 2.684-6.615z" fill="#4285F4"/>
                <path d="M9.003 18c2.43 0 4.467-.806 5.956-2.18L12.05 13.56c-.806.54-1.836.86-3.047.86-2.344 0-4.328-1.584-5.036-3.711H.96v2.332C2.438 15.983 5.482 18 9.003 18z" fill="#34A853"/>
                <path d="M3.964 10.712c-.18-.54-.282-1.117-.282-1.71 0-.593.102-1.17.282-1.71V4.96H.957C.347 6.175 0 7.55 0 9.002c0 1.452.348 2.827.957 4.042l3.007-2.332z" fill="#FBBC05"/>
                <path d="M9.003 3.58c1.321 0 2.508.454 3.44 1.345l2.582-2.58C13.464.891 11.426 0 9.003 0 5.482 0 2.438 2.017.96 4.958L3.967 7.29c.708-2.127 2.692-3.71 5.036-3.71z" fill="#EA4335"/>
              </svg>
              Connexion avec Google
            </button>

            <button type="button" className="social-btn facebook-btn">
              <svg width="18" height="18" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z" fill="#1877F2"/>
              </svg>
              Connexion avec Facebook
            </button>
          </div>
        </form>
      </div>
      
    </div>
  );
};

export default AuthUser;
