// frontend-react/src/components/ChatExample.tsx
import React from 'react';
import ChatExampleImage from '../assets/img/valeurs/JOUR_2.webp';

const ChatExample: React.FC = () => {
  return (
    <div className="chat-example">
      <div className="chat-window">
        <img
          className="chat-image"
          src={ChatExampleImage}
          alt="Exemple de chat"
        />
      </div>
    </div>
  );
};

export default ChatExample;

// max/src/components/ChatExample.vue
<template>
  <div class="chat-example">
    <div class="chat-window">
<img style="    width: 100%;margin-left: 61px;" src="../assets/img/valeurs/JOUR_1.webp" alt="">
    </div>
  </div>
</template>

<style scoped>
.chat-example {
  flex: 1;
}

.chat-window {
  border-radius: 20px;
  padding: 2rem;
  backdrop-filter: blur(10px);
  min-height: 400px;
}

h4 {
  text-align: center;
  margin-bottom: 1rem;
  font-size: 1.2rem;
}
</style>
