// frontend-react/src/components/Mail.tsx
import React, { useState, ChangeEvent, FormEvent } from 'react';
import { collection, addDoc } from 'firebase/firestore';
import { db } from '../firebaseConfig';

interface FormData {
  prenom: string;
  nom: string;
  age: string;
  email: string;
  telephone: string;
}

const Mail: React.FC = () => {
  const [formData, setFormData] = useState<FormData>({
    prenom: '',
    nom: '',
    age: '',
    email: '',
    telephone: ''
  });

  const [isSubmitting, setIsSubmitting] = useState<boolean>(false);
  const [message, setMessage] = useState<string>('');
  const [messageType, setMessageType] = useState<string>(''); // 'success' ou 'error'

  const resetForm = (): void => {
    setFormData({
      prenom: '',
      nom: '',
      age: '',
      email: '',
      telephone: ''
    });
  };

  const handleInputChange = (e: ChangeEvent<HTMLInputElement>): void => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
  };

  const submitForm = async (e: FormEvent<HTMLFormElement>): Promise<void> => {
    e.preventDefault();
    setIsSubmitting(true);
    setMessage('');

    try {
      const newsletterRef = collection(db, 'newsletter');
      const docRef = await addDoc(newsletterRef, {
        ...formData,
        dateInscription: new Date()
      });
      
      console.log('Document written with ID: ', docRef.id);
      setMessage('Inscription réussie !');
      setMessageType('success');
      resetForm();
    } catch (error: unknown) {
      const firebaseError = error as Error;
      console.error('Erreur détaillée:', firebaseError.message);
      setMessage('Une erreur est survenue lors de l\'inscription');
      setMessageType('error');
    } finally {
      setIsSubmitting(false);
      
      // Effacer le message après 5 secondes
      setTimeout(() => {
        setMessage('');
        setMessageType('');
      }, 5000);
    }
  };

  return (
    <div className="py-20 px-8 bg-gradient-purple">
      <h1 className="text-title font-bold text-white text-center mb-12 font-ubuntu">Restez informé de nos actualités</h1>
      <form onSubmit={submitForm} className="max-w-3xl mx-auto space-y-6">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="space-y-4">
            <input 
              name="prenom"
              value={formData.prenom}
              onChange={handleInputChange}
              type="text" 
              placeholder="Prénom"
              className="w-full px-6 py-4 rounded-4xl border border-white/20 bg-white text-purple-dark placeholder-purple-dark/55 focus:outline-none focus:ring-2 focus:ring-primary-yellow font-ubuntu disabled:opacity-60"
              required
              disabled={isSubmitting}
            />
            <input 
              name="nom"
              value={formData.nom}
              onChange={handleInputChange}
              type="text" 
              placeholder="Nom"
              className="w-full px-6 py-4 rounded-4xl border border-white/20 bg-white text-purple-dark placeholder-purple-dark/55 focus:outline-none focus:ring-2 focus:ring-primary-yellow font-ubuntu disabled:opacity-60"
              required
              disabled={isSubmitting}
            />
          </div>
          
          <div className="space-y-4">
            <input 
              name="age"
              value={formData.age}
              onChange={handleInputChange}
              type="number" 
              placeholder="Âge"
              className="w-full px-6 py-4 rounded-4xl border border-white/20 bg-white text-purple-dark placeholder-purple-dark/55 focus:outline-none focus:ring-2 focus:ring-primary-yellow font-ubuntu disabled:opacity-60"
              required
              min="13"
              disabled={isSubmitting}
            />
            <input 
              name="email"
              value={formData.email}
              onChange={handleInputChange}
              type="email" 
              placeholder="Email"
              className="w-full px-6 py-4 rounded-4xl border border-white/20 bg-white text-purple-dark placeholder-purple-dark/55 focus:outline-none focus:ring-2 focus:ring-primary-yellow font-ubuntu disabled:opacity-60"
              required
              disabled={isSubmitting}
            />
          </div>
          
          <div className="md:col-span-2">
            <input 
              name="telephone"
              value={formData.telephone}
              onChange={handleInputChange}
              type="tel" 
              placeholder="Numéro de téléphone"
              className="w-full px-6 py-4 rounded-4xl border border-white/20 bg-white text-purple-dark placeholder-purple-dark/55 focus:outline-none focus:ring-2 focus:ring-primary-yellow font-ubuntu disabled:opacity-60"
              required
              disabled={isSubmitting}
            />
          </div>

          {message && (
            <div className={`md:col-span-2 px-4 py-3 rounded-lg text-center font-ubuntu ${messageType === 'success' ? 'bg-green-500/20 border border-green-500 text-green-100' : 'bg-red-500/20 border border-red-500 text-red-100'}`}>
              {message}
            </div>
          )}
          
          <button type="submit" className="md:col-span-2 w-full bg-primary-yellow text-purple-dark border-none px-10 py-4 rounded-full text-body font-semibold cursor-pointer transition-all duration-300 hover:bg-primary-yellow-dark hover:shadow-card-hover disabled:opacity-50 disabled:cursor-not-allowed font-ubuntu" disabled={isSubmitting}>
            {isSubmitting ? 'Inscription en cours...' : 'S\'inscrire à la newsletter'}
          </button>
        </div>
      </form>
    </div>
  );
};

export default Mail;

// max/src/components/Mail.vue

<script>
import { ref } from 'vue'
import { collection, addDoc } from 'firebase/firestore'
import { db } from '../firebaseConfig'


export default {
  name: 'NewsletterForm',
  setup() {
  

    const formData = ref({
      prenom: '',
      nom: '',
      age: '',
      email: '',
      telephone: ''
    })

    const resetForm = () => {
      formData.value = {
        prenom: '',
        nom: '',
        age: '',
        email: '',
        telephone: ''
      }
    }

    const submitForm = async () => {
      try {
        const newsletterRef = collection(db, 'newsletter')
        const docRef = await addDoc(newsletterRef, {
          ...formData.value,
          dateInscription: new Date()
        })
        console.log("Document written with ID: ", docRef.id) // Pour debug
        alert('Inscription réussie !')
        resetForm() // Réinitialise le formulaire après succès
      } catch (error) {
        console.error("Erreur détaillée:", error.message)
        alert("Une erreur est survenue lors de l'inscription")
      }
    }

    return {
      formData,
      submitForm
    }
  }
}
</script>
<template>
  <div class="newsletter-section">
    <h1>Restez informé de nos actualités</h1>
    <form @submit.prevent="submitForm" class="newsletter-form">
    <div class="form-row"> 
      <div class="form-group">
        <input 
          v-model="formData.prenom" 
          type="text" 
          placeholder="Prénom"
          required
        >
        <input 
          v-model="formData.nom" 
          type="text" 
          placeholder="Nom"
          required
        >
      </div>
      <div class="form-group">
        <input 
          v-model="formData.age" 
          type="number" 
          placeholder="Âge"
          required
          min="13"
        >
        <input 
          v-model="formData.email" 
          type="email" 
          placeholder="Email"
          required
        >
      </div>
      <div class="form-group">
        <input 
          v-model="formData.telephone" 
          type="tel" 
          placeholder="Numéro de téléphone"
          required
        >
      </div>
      <button type="submit" class="submit-btn">S'inscrire à la newsletter</button>
    </div>

    </form>
  </div>
</template>


<style scoped>
.newsletter-section {
  background: #1C5372;
  padding: 4rem 2rem;
  color: white;
  text-align: center;
}

.newsletter-content {
  max-width: 800px;
  margin: 0 auto;
  text-align: center;
}

h1 {
  font-size: 2rem;
  margin-bottom: 1rem;
}

.tagline {
  font-size: 1.1rem;
  margin-bottom: 2rem;
  opacity: 0.9;
}

.newsletter-form {
  background: rgba(255, 255, 255, 0.1);
  padding: 2rem;
  border-radius: 20px;
  backdrop-filter: blur(10px);
}


.form-row {
  display: flex;
  justify-content: space-between;
  flex-direction: column;
}


input {
  width: 100%;
  padding: 0.75rem 1rem;
  border: none;
  border-radius: 25px;
  margin-bottom: 1rem;

  background: rgba(255, 255, 255, 0.9);
  font-size: 1rem;
  color: black;
}

input::placeholder {
  color: #666;
}

.submit-btn {
  background: #90DBF5;
  color: #1C5372;
  border: none;
  padding: 1rem 2rem;
  border-radius: 25px;
  font-size: 1rem;
  cursor: pointer;
  transition: all 0.3s;
  margin-top: 1rem;
  font-weight: 600;
}

.submit-btn:hover:not(:disabled) {
  background: #7BC8E2;
}

.submit-btn:disabled {
  opacity: 0.7;
  cursor: not-allowed;
}

.success-message {
  background: rgba(75, 181, 67, 0.2);
  color: #4BB543;
  padding: 1rem;
  border-radius: 10px;
  margin: 1rem 0;
}

.error-message {
  background: rgba(255, 0, 0, 0.2);
  color: #FF0000;
  padding: 1rem;
  border-radius: 10px;
  margin: 1rem 0;
}


.submit-btn {
  background-color: #1C5372;
  color: white;
  padding: 1rem 2rem;
  border: none;
  border-radius: 5px;
  font-size: 1rem;
  cursor: pointer;
  transition: background-color 0.3s;
}

.submit-btn:hover {
  background-color: #164259;
}

@media (max-width: 768px) {
  .form-group {
    flex-direction: column;
  }
}
</style>
