// frontend-react/src/components/NotFound.jsx
import React from 'react';
import { Link } from 'react-router-dom';

const NotFound = () => {
  return (
    <div style={{ 
      display: 'flex', 
      flexDirection: 'column', 
      alignItems: 'center', 
      justifyContent: 'center', 
      height: '100vh',
      textAlign: 'center'
    }}>
      <h1>404 - Page non trouvée</h1>
      <p>La page que vous cherchez n'existe pas.</p>
      <Link to="/" style={{ color: '#3b82f6', textDecoration: 'none' }}>
        Retour à l'accueil
      </Link>
    </div>
  );
};

export default NotFound;

// max/src/components/NotFound.vue
<template>
    <div class="not-found">
      <h1>404 - Page non trouvée</h1>
      <p>La page que vous recherchez n'existe pas.</p>
      <router-link to="/">Retour à l'accueil</router-link>
    </div>
  </template>
  <script>
  export default {
    name: 'NotFound'
  }
  </script>
  <style scoped>
  .not-found {
    text-align: center;
    padding: 50px;
  }
  </style>
